# Generated by pointblank

tbl <- fz_data

test_that("column `date` exists", {

  expect_col_exists(
    tbl,
    columns = vars(date),
    threshold = 1
  )
})

test_that("column `date` is of type: Date", {

  expect_col_is_date(
    tbl,
    columns = vars(date),
    threshold = 1
  )
})

test_that("all columns but `date` are of type: numeric", {

  expect_col_is_numeric(
    tbl,
    columns = 2:ncol(tbl),
    threshold = 1
  )
})
